// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as JsxRuntime from "react/jsx-runtime";

function Blanket(props) {
  var onClick = props.onClick;
  return JsxRuntime.jsx("div", {
              style: {
                bottom: "0",
                left: "0",
                position: "fixed",
                right: "0",
                top: "0",
                zIndex: "1"
              },
              onClick: (function (param) {
                  Curry._1(onClick, undefined);
                })
            });
}

var make = Blanket;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
