// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Theme from "./Theme.bs.mjs";
import * as Blanket from "./Blanket.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function DropDown$Menu(props) {
  return JsxRuntime.jsx("div", {
              children: props.children,
              style: {
                background: Theme.background,
                marginTop: "3px",
                position: "absolute",
                zIndex: "2",
                borderRadius: "2px",
                boxShadow: "0px 3px 18px 0px rgba(0, 0, 0, 0.15), 0px 0px 0px 1px rgba(0, 0, 0, 0.08)"
              }
            });
}

var Menu = {
  make: DropDown$Menu
};

var fontStyles_color = Theme.colors.text.primary;

var fontStyles_fontFamily = "Arial";

var fontStyles_fontSize = "14px";

var fontStyles_fontWeight = "400";

var fontStyles_lineHeight = "18px";

var fontStyles = {
  color: fontStyles_color,
  fontFamily: fontStyles_fontFamily,
  fontSize: fontStyles_fontSize,
  fontWeight: fontStyles_fontWeight,
  lineHeight: fontStyles_lineHeight
};

function DropDown(props) {
  var isOpen = props.isOpen;
  return JsxRuntime.jsxs("div", {
              children: [
                props.target,
                isOpen ? JsxRuntime.jsx(DropDown$Menu, {
                        children: props.children
                      }) : null,
                isOpen ? JsxRuntime.jsx(Blanket.make, {
                        onClick: props.onClose
                      }) : null
              ],
              style: fontStyles
            });
}

var make = DropDown;

export {
  Menu ,
  fontStyles ,
  make ,
}
/* fontStyles Not a pure module */
