// Generated by ReScript, PLEASE EDIT WITH CARE


var colors = {
  text: {
    primary: "#333333",
    secondary: "#00000085",
    placeholder: "#00000052"
  }
};

var border = "1px solid rgba(0, 0, 0, 0.20)";

var background = "#ffffff";

export {
  colors ,
  border ,
  background ,
}
/* No side effect */
