// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as CountryAPI from "./CountryAPI.bs.mjs";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Core__Promise from "@rescript/core/src/Core__Promise.bs.mjs";
import * as CountrySelect from "./countrySelect/CountrySelect.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  var match = React.useState(function () {
        
      });
  var setStatus = match[1];
  React.useEffect((function () {
          Curry._1(setStatus, (function (param) {
                  return /* Loading */0;
                }));
          Core__Promise.$$catch(CountryAPI.getCountries(undefined).then(function (options) {
                    Curry._1(setStatus, (function (param) {
                            return {
                                    TAG: /* Ok */0,
                                    _0: options
                                  };
                          }));
                    return Promise.resolve(undefined);
                  }), (function (exn) {
                  Curry._1(setStatus, (function (param) {
                          return {
                                  TAG: /* Error */1,
                                  _0: exn
                                };
                        }));
                  return Promise.resolve(undefined);
                }));
        }), []);
  return JsxRuntime.jsx("div", {
              children: Belt_Option.getWithDefault(Belt_Option.map(match[0], (function (options) {
                          if (typeof options === "number") {
                            return JsxRuntime.jsx("div", {
                                        children: "Loading"
                                      });
                          } else if (options.TAG === /* Ok */0) {
                            return JsxRuntime.jsx(CountrySelect.make, {
                                        options: options._0
                                      });
                          } else {
                            return JsxRuntime.jsx("div", {
                                        children: "Error"
                                      });
                          }
                        })), null),
              className: "p-6"
            });
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
