// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Json$JsonCombinators from "@glennsl/rescript-json-combinators/src/Json.bs.mjs";
import * as Json_Decode$JsonCombinators from "@glennsl/rescript-json-combinators/src/Json_Decode.bs.mjs";

var url = "https://gist.githubusercontent.com/rusty-key/659db3f4566df459bd59c8a53dc9f71f/raw/4127f9550ef063121c564025f6d27dceeb279623/counties.json";

var option = Json_Decode$JsonCombinators.object(function (field) {
      return {
              label: field.required("label", Json_Decode$JsonCombinators.string),
              value: field.required("value", Json_Decode$JsonCombinators.string)
            };
    });

var Decode = {
  option: option
};

async function getCountries(param) {
  var response = await fetch(url, {
        method: "GET"
      });
  var jsonResult = await response.json();
  var options = Json$JsonCombinators.decode(jsonResult, Json_Decode$JsonCombinators.array(option));
  if (options.TAG === /* Ok */0) {
    return options._0;
  } else {
    return Js_exn.raiseError(options._0);
  }
}

export {
  url ,
  Decode ,
  getCountries ,
}
/* option Not a pure module */
